import { safqaAssetKeys } from '../../config/safqaAssets'
import type { Locale, SafqaLandingCopy } from './safqaLandingTypes'

export const safqaLandingCopy: Record<Locale, SafqaLandingCopy> = {
  ar: {
    brand: 'صفقة',
    switchLanguage: 'English',
    nav: {
      home: 'الرئيسية',
      decision: 'القرار السريع',
      paths: 'من المستفيد؟',
      opportunities: 'الفرص المتاحة',
      howItWorks: 'كيف نعمل؟',
      process: 'رحلة التنازل',
      brokers: 'للبروكرز',
    },
    hero: {
      eyebrow: 'منصة التنازل عن وحدات التقسيط — بدون أوفر',
      title: 'صفقة للتنازل العقاري',
      body: 'البايع يسترجع كل اللي دفعه كاش، والمشتري ياخد سعر التعاقد القديم. كل الأرقام متحققة بالمستندات.',
      primaryCta: 'بيع وحدتك',
      secondaryCta: 'شوف فرص الشراء',
      proofLabel: 'كل رقم',
      proofValue: 'بمستند',
      heroCard: {
        cancelTitle: 'لو رجّع الوحدة للمطور',
        cancelDeductLabel: 'خصم الإلغاء (15% من سعر الوحدة كله)',
        cancelDeductValue: '- 1,500,000 ج.م',
        cancelGetLabel: 'اللي هيرجعله',
        cancelGetValue: '500,000 ج.م',
        cancelYearsLabel: 'ياخدها على',
        cancelYearsValue: '3 سنين',
        cancelNote: 'خسارة 75% من فلوسه + سنين انتظار',
        vsLabel: 'VS',
        transferTitle: 'لو نقل تعاقده عن طريق صفقة',
        transferGetLabel: 'يسترجع اللي دفعه',
        transferGetValue: '2,000,000 ج.م',
        transferGetSub: 'كاش عند إتمام النقل',
        transferNote: 'فلوسه كاملة، والمشتري كسب سعر قديم',
      },
    },
    search: {
      title: 'دور على فرصة موثقة',
      location: 'الموقع أو الكمبوند',
      type: 'نوع الوحدة',
      status: 'حالة الصفقة',
      submit: 'ابحث',
    },
    stats: [
      { value: '305+', label: 'ملف تمت مراجعته' },
      { value: '1090+', label: 'فرصة مفهرسة' },
      { value: '67', label: 'بروكر متعاون' },
      { value: '15%', label: 'خسارة ممكن تتجنبها' },
    ],
    sellerBuyer: {
      eyebrow: 'مين المستفيد؟',
      title: 'طرف محتاج يبيع، وطرف مستني الفرصة — وإحنا بنوصّلهم',
      subtitle: 'ده مش ريسيل عادي: مفيش أوفر خالص. البايع بياخد اللي دفعه بالظبط، والمشتري بياخد سعر التعاقد القديم زي ما هو',
      seller: {
        tag: 'البايع — صاحب الوحدة',
        title: 'بدون أوفر = أسرع بيع في السوق',
        body: 'لأن سعرك هو نفس اللي دفعته من غير أي زيادة، وحدتك بتبقى أحسن فرصة قدام المشترين — فبتتباع أسرع. تسترجع فلوسك كاملة كاش، بدل ما المطور يخصم منك ويقسّط لك الباقي على سنين.',
        features: [
          'تسترجع 100% من اللي دفعته — كاش عند إتمام التنازل',
          'من غير إعلانات علنية ولا تليفونات سماسرة',
          'بنجهّز معاك ملف التنازل ونتابع معاك خطوة بخطوة لحد الإمضاء',
        ],
        freeNote: 'مجانًا عليك تمامًا — صفقة مش بتاخد أي عمولة من البايع.',
        cta: 'اعرض وحدتك للتنازل',
      },
      buyer: {
        tag: 'المشتري',
        title: 'وحدة بالتقسيط من غير ما تدفع أوفر لحد',
        body: 'بتاخد الوحدة بسعر تعاقدها القديم — أرخص من سعر المطور النهارده بفرق كبير — وتكمّل الأقساط العادية. الفرق ده مكسبك من يوم ما تمضي.',
        features: [
          'سعر التعاقد القديم زي ما هو — الأوفر ممنوع على المنصة',
          'العقد والمدفوعات والمتبقي متحقق منهم قبل ما تشوف الفرصة',
          'تنازل رسمي معتمد من المطور — مش توكيلات وكلام',
        ],
        cta: 'شوف الفرص المتاحة',
      },
    },
    comparison: {
      eyebrow: 'الفرق الحقيقي',
      title: 'إيه الفرق بيننا وبين الريسيل العادي؟',
      subtitle: 'السوق مليان إعلانات وسماسرة — إحنا بنشتغل بطريقة تانية خالص',
      rows: [
        { label: 'السعر', regular: 'أوفر فوق السعر، ومبالغة عشان الفصال', safqa: 'بدون أوفر — السعر = اللي اتدفع فعلًا، موثق بالإيصالات' },
        { label: 'الأرقام', regular: 'كلام البايع والسمسار من غير دليل', safqa: 'متحققين من العقد والمدفوعات والمتبقي — بالمستندات الرسمية' },
        { label: 'الإجراءات', regular: 'السمسار بيوصّلك وبعدين انت وحظك', safqa: 'بنمشي معاك في كل خطوات التنازل لحد الإمضاء والقبض' },
        { label: 'العمولة', regular: 'سعي وسمسرة من الطرفين في كل خطوة ومفاجآت', safqa: 'مجانًا للبايع — 1.25% على المشتري بس، وعند إتمام التنازل فقط' },
      ],
    },
    numbersExample: {
      eyebrow: 'مثال حقيقي',
      title: 'مثال بالأرقام',
      subtitle: 'وحدة سعرها الإجمالي 10 مليون جنيه، صاحبها دفع منها 2 مليون على 3 سنين وموقف عن السداد',
      cancelCard: {
        title: 'لو رجّع الوحدة للمطور',
        deductLabel: 'خصم الإلغاء (15% من سعر الوحدة كله)',
        deductValue: '- 1,500,000 ج.م',
        getLabel: 'اللي هيرجعله',
        getValue: '500,000 ج.م',
        yearsLabel: 'ياخدها على',
        yearsValue: '3 سنين',
        note: 'خسارة 75% من فلوسه + سنين انتظار',
      },
      transferCard: {
        title: 'لو نقل تعاقده عن طريق صفقة',
        getLabel: 'يسترجع اللي دفعه',
        getValue: '2,000,000 ج.م',
        getSub: 'كاش عند إتمام النقل',
        feeLabel: 'عمولة صفقة عليك كبايع',
        feeValue: 'صفر',
        feeSub: 'تدفع صفر — تستلم اللي دفعته بالكامل',
        note: 'فلوسه كاملة، والمشتري كسب سعر قديم',
      },
      disclaimer: 'الأرقام دي مثال توضيحي. نسبة الخصم وشروط الاسترداد بتختلف من عقد لعقد — وده بالظبط اللي بنراجعه في تقرير الخروج المجاني.',
    },
    paths: {
      eyebrow: 'المسارات',
      title: 'ثلاث مشاكل وحل واحد واضح',
      items: [
        {
          title: 'مالك متعثر',
          body: 'بدل ما تلغي العقد وتخسر، اعرض وحدتك للتنازل بأرقام مراجعة.',
          action: 'قيّم وحدتك',
        },
        {
          title: 'مشتري فرصة',
          body: 'اشتري بسعر تعاقد قديم أقل من السوق وكمل الأقساط بوضوح.',
          action: 'شوف الوحدات',
        },
        {
          title: 'بروكر فريلانسر',
          body: 'سجل العقد وإحنا نراجعه ونقفله ونتابع عمولتك.',
          action: 'سجل عقد',
        },
      ],
    },
    howItWorks: {
      eyebrow: 'إزاي بنشتغل',
      title: 'إزاي بنشتغل؟',
      subtitle: 'خمس خطوات واضحة، ومسؤول حالة معاك في كل خطوة',
      steps: [
        { title: 'قيّم عقدك', body: 'دخّل بيانات عقدك واعرف موقفك مجانًا — وأول ما تبعت طلبك، حسابك بيتجهز تلقائيًا' },
        { title: 'ارفع مستنداتك', body: 'العقد وإيصالات السداد — بنراجعها ونتحقق منها' },
        { title: 'بنجهّز فرصتك', body: 'بنتحقق من الأرقام بالمستندات ونجهز عرض موثوق للمشترين' },
        { title: 'بنلاقي المشتري', body: 'بنطابق وحدتك مع مشترين قادرين فعلًا يكمّلوا' },
        { title: 'نقل التعاقد', body: 'بنمشي معاك في إجراءات النقل خطوة بخطوة لحد ما تقبض' },
      ],
    },
    fairExit: {
      eyebrow: 'مبادئنا',
      title: 'معايير الخروج العادل',
      subtitle: 'وضعنا قواعد ملزمة لنفسنا قبل ما نطلبك تثق فينا',
      items: [
        { title: 'كل رقم له مصدر', body: 'بنوضحلك إيه المؤكد بالمستندات وإيه التقديري — من غير وعود مضللة' },
        { title: 'مجانًا للبايع بالكامل', body: 'مفيش أي عمولة على البايع خالص. المشتري بيدفع 1.25% عند إتمام النقل بس — من غير أي رسوم مخفية' },
        { title: 'خصوصيتك محفوظة', body: 'تقدر تختار الخروج الصامت — مفيش إعلان علني ولا تليفونات مزعجة' },
        { title: 'من غير ضغط', body: 'بنعرض عليك كل الخيارات — حتى لو الأفضل ليك إنك تكمّل تعاقدك' },
      ],
    },
    calculatorCta: {
      title: 'اعرف موقفك في دقيقة',
      subtitle: 'دخّل سعر الوحدة واللي دفعته، وشوف الفرق بين الإلغاء ونقل التعاقد',
      cta: 'احسب دلوقتي',
    },
    dualCta: {
      seller: {
        title: 'مش قادر تكمّل أقساطك؟',
        body: 'متتسرعش في قرار الإلغاء. اعرف موقفك الأول — التقييم مجاني ومن غير أي التزام.',
        cta: 'ابدأ تقييم عقدك',
      },
      buyer: {
        title: 'بتدوّر على فرصة حقيقية؟',
        body: 'سجّل ميزانيتك وهنبعتلك الفرص اللي تناسب الكاش المتاح معاك والقسط اللي يريحك.',
        cta: 'سجّل كمشتري',
      },
    },
    opportunities: {
      eyebrow: 'عروض مختارة',
      title: 'فرص تنازل جاهزة للفحص',
      items: [
        {
          id: 'unit-1',
          imageKey: safqaAssetKeys.propertyOne,
          gallery: [safqaAssetKeys.propertyOne, safqaAssetKeys.propertyTwo, safqaAssetKeys.listingOne],
          title: 'وحدة جاهزة للتنازل',
          location: 'القاهرة الجديدة',
          price: '3,950,000',
          oldPrice: '4,800,000',
          meta: '145 م2 / شقة',
          badge: 'مستندات متحققة',
          type: 'apartment',
          description: 'شقة سكنية مميزة في موقع استراتيجي بالقاهرة الجديدة، تصميم عصري وإطلالة بانورامية رائعة، بالقرب من كافة الخدمات.',
          amenities: ['أمن وحراسة 24/7', 'حمام سباحة', 'موقف سيارات خاص', 'نادي صحي'],
          bedrooms: '3',
          bathrooms: '2',
          remainingPrice: '1,850,000',
          installment: '120,000',
          frequency: 'ربع سنوي',
          deliveryYear: '2026',
          unitCode: 'U-11311',
          developer: 'إعمار مصر',
          project: 'ميفيدا',
          floor: 'الأول',
          contractYear: '2023',
          marketPrice: '7,500,000',
          meterPrice: '27,241',
        },
        {
          id: 'unit-2',
          imageKey: safqaAssetKeys.propertyTwo,
          gallery: [safqaAssetKeys.propertyTwo, safqaAssetKeys.listingTwo, safqaAssetKeys.propertyFour],
          title: 'فرصة بسعر أقل من السوق',
          location: 'الشيخ زايد',
          price: '5,100,000',
          oldPrice: '6,200,000',
          meta: '210 م2 / تاون هاوس',
          badge: 'تحت المراجعة',
          type: 'townhouse',
          description: 'تاون هاوس واسع في قلب الشيخ زايد، يتميز بحديقة خاصة وموقع هادئ مناسب للعائلات.',
          amenities: ['حديقة خاصة', 'منطقة ألعاب أطفال', 'نادي رياضي'],
          bedrooms: '4',
          bathrooms: '3',
          remainingPrice: '3,200,000',
          installment: '200,000',
          frequency: 'ربع سنوي',
          deliveryYear: '2027',
          unitCode: 'U-11312',
          developer: 'سوديك',
          project: 'فيليت',
          floor: 'أرضي بحديقة',
          contractYear: '2024',
          marketPrice: '9,800,000',
          meterPrice: '24,285',
        },
        {
          id: 'unit-3',
          imageKey: safqaAssetKeys.propertyThree,
          gallery: [safqaAssetKeys.propertyThree, safqaAssetKeys.propertyOne, safqaAssetKeys.listingThree],
          title: 'عقد بروكر قابل للإغلاق',
          location: 'العاصمة الإدارية',
          price: '2,850,000',
          oldPrice: '3,400,000',
          meta: '118 م2 / شقة',
          badge: 'عمولة محفوظة',
          type: 'apartment',
          description: 'شقة فاخرة في العاصمة الإدارية الجديدة، فرصة استثمارية رائعة مع تسهيلات في السداد.',
          amenities: ['سمارت هوم', 'جيم', 'سبا'],
          bedrooms: '2',
          bathrooms: '2',
          remainingPrice: '1,450,000',
          installment: '95,000',
          frequency: 'ربع سنوي',
          deliveryYear: '2026',
          unitCode: 'U-11313',
          developer: 'طلعت مصطفى',
          project: 'سيليا',
          floor: 'الثاني',
          contractYear: '2023',
          marketPrice: '4,900,000',
          meterPrice: '24,152',
        },
        {
          id: 'unit-4',
          imageKey: safqaAssetKeys.propertyFour,
          gallery: [safqaAssetKeys.propertyFour, safqaAssetKeys.listingOne, safqaAssetKeys.propertyTwo],
          title: 'شاليه على البحر للتنازل',
          location: 'الساحل الشمالي',
          price: '6,200,000',
          oldPrice: '7,800,000',
          meta: '130 م2 / شاليه',
          badge: 'جدية مؤكدة',
          type: 'chalet',
          description: 'شاليه فاخر يطل مباشرة على البحر في الساحل الشمالي، قرية متكاملة الخدمات.',
          amenities: ['إطلالة بحر', 'أكوا بارك', 'مطاعم وكافيهات'],
          bedrooms: '3',
          bathrooms: '2',
          remainingPrice: '4,500,000',
          installment: '310,000',
          frequency: 'ربع سنوي',
          deliveryYear: '2027',
          unitCode: 'U-11314',
          developer: 'تطوير مصر',
          project: 'سولت',
          floor: 'الأول',
          contractYear: '2024',
          marketPrice: '12,500,000',
          meterPrice: '47,692',
        },
        {
          id: 'unit-5',
          imageKey: safqaAssetKeys.listingOne,
          gallery: [safqaAssetKeys.listingOne, safqaAssetKeys.propertyThree, safqaAssetKeys.listingTwo],
          title: 'شقة تشطيب كامل استلاف فوري',
          location: '6 أكتوبر',
          price: '3,100,000',
          oldPrice: '3,800,000',
          meta: '155 م2 / شقة',
          badge: 'مستندات متحققة',
          type: 'apartment',
          description: 'شقة بتشطيبات الترا سوبر لوكس جاهزة للسكن فوراً في منطقة راقية بـ 6 أكتوبر.',
          amenities: ['تشطيب كامل', 'مصعد', 'أمن'],
          bedrooms: '3',
          bathrooms: '3',
          remainingPrice: '1,200,000',
          installment: '80,000',
          frequency: 'ربع سنوي',
          deliveryYear: '2025',
          unitCode: 'U-11315',
          developer: 'أوراسكوم',
          project: 'أو ويست',
          floor: 'الثالث',
          contractYear: '2022',
          marketPrice: '5,500,000',
          meterPrice: '20,000',
        },
        {
          id: 'unit-6',
          imageKey: safqaAssetKeys.listingTwo,
          gallery: [safqaAssetKeys.listingTwo, safqaAssetKeys.propertyFour, safqaAssetKeys.listingThree],
          title: 'توين هاوس بالتقسيط المريح',
          location: 'الشيخ زايد',
          price: '8,500,000',
          oldPrice: '10,500,000',
          meta: '280 م2 / توين هاوس',
          badge: 'جدية مؤكدة',
          type: 'twinhouse',
          description: 'توين هاوس فخم بتصميم مودرن، يوفر مساحات واسعة وراحة متكاملة بأسلوب سداد مرن جداً.',
          amenities: ['مساحات خضراء', 'منطقة شواء', 'جراج سيارتين'],
          bedrooms: '5',
          bathrooms: '4',
          remainingPrice: '5,600,000',
          installment: '350,000',
          frequency: 'ربع سنوي',
          deliveryYear: '2028',
          unitCode: 'U-11316',
          developer: 'إعمار مصر',
          project: 'كايرو جيت',
          floor: 'أرضي بحديقة',
          contractYear: '2024',
          marketPrice: '16,500,000',
          meterPrice: '30,357',
        },
        {
          id: 'unit-7',
          imageKey: safqaAssetKeys.listingThree,
          gallery: [safqaAssetKeys.listingThree, safqaAssetKeys.propertyOne, safqaAssetKeys.listingOne],
          title: 'فيلا مستقلة بأقل مقدم',
          location: 'القاهرة الجديدة',
          price: '11,200,000',
          oldPrice: '13,500,000',
          meta: '360 م2 / فيلا',
          badge: 'تحت المراجعة',
          type: 'villa',
          description: 'فيلا مستقلة بمساحات شاسعة في أرقى كمبوندات القاهرة الجديدة، استمتع بالخصوصية والرفاهية المطلقة.',
          amenities: ['مسبح خاص', 'غرفة خادمة', 'حديقة كبيرة', 'سمارت هوم'],
          bedrooms: '6',
          bathrooms: '5',
          remainingPrice: '6,800,000',
          installment: '450,000',
          frequency: 'ربع سنوي',
          deliveryYear: '2027',
          unitCode: 'U-11317',
          developer: 'ماونتن فيو',
          project: 'اي سيتي',
          floor: 'أرضي مستقل',
          contractYear: '2023',
          marketPrice: '22,000,000',
          meterPrice: '31,111',
        },
        {
          id: 'unit-8',
          imageKey: safqaAssetKeys.propertyOne,
          gallery: [safqaAssetKeys.propertyOne, safqaAssetKeys.listingTwo, safqaAssetKeys.propertyThree],
          title: 'شاليه بقرية متكاملة الخدمات',
          location: 'العين السخنة',
          price: '2,400,000',
          oldPrice: '3,100,000',
          meta: '95 م2 / شاليه',
          badge: 'عمولة محفوظة',
          type: 'chalet',
          description: 'شاليه مصيفي رائع في العين السخنة بخدمات فندقية متكاملة، مثالي للعطلات العائلية القصيرة.',
          amenities: ['خدمة فندقية', 'شاطئ خاص', 'كيدز إريا'],
          bedrooms: '2',
          bathrooms: '1',
          remainingPrice: '1,100,000',
          installment: '75,000',
          frequency: 'ربع سنوي',
          deliveryYear: '2026',
          unitCode: 'U-11318',
          developer: 'المطورون العرب',
          project: 'بورتو سخنة',
          floor: 'الثاني',
          contractYear: '2023',
          marketPrice: '4,200,000',
          meterPrice: '25,263',
        }
      ],
    },
    process: {
      eyebrow: 'رحلة التنازل',
      title: 'خطوات واضحة لحد الإتمام',
      body: 'من أول مراجعة العقد لحد التوقيع وصرف العمولة.',
      items: [
        { title: 'فحص الورق', body: 'العقد، الإيصالات، وجدول الأقساط.' },
        { title: 'تثبيت الأرقام', body: 'المدفوع، المتبقي، وتكلفة التنازل.' },
        { title: 'الإغلاق', body: 'متابعة التوقيع وحالة الصفقة.' },
      ],
    },
    broker: {
      eyebrow: 'للبروكرز',
      title: 'هات الصفقة وإحنا نقفلها',
      body: 'البروكر المستقل يدخل عقده، يتابع الحالة، ويشوف عمولته بوضوح.',
      cards: [
        { value: '24h', label: 'مراجعة أولية' },
        { value: '9d', label: 'متوسط إغلاق' },
        { value: '100%', label: 'حالة موثقة' },
      ],
    },
    command: {
      eyebrow: 'غرفة الصفقة',
      title: 'متابعة واحدة لكل عقد',
      body: 'العميل، الوحدة، المدفوع، المتبقي، المستندات، وحالة التنازل في شاشة واحدة.',
      metrics: [
        { value: '43', label: 'ملف تحت الفحص' },
        { value: '28', label: 'إجراء تنازل' },
        { value: 'EGP 620K', label: 'عمولات قيد الصرف' },
      ],
      queue: [
        { title: 'East Residence A-1407', meta: 'عقد بروكر / 5.8M', status: 'مراجعة' },
        { title: 'West Park T-22', meta: 'تنازل / 9.4M', status: 'حجز تنازل' },
        { title: 'Capital Line B-08', meta: 'فرصة مشتري / 4.1M', status: 'جاهز' },
      ],
    },
    guarantees: {
      eyebrow: 'التوثيق',
      title: 'مفيش رقم من غير مستند',
      items: [
        {
          title: 'فحص العقد',
          body: 'نراجع شروط الإلغاء، التنازل، وأي غرامات ممكنة.',
        },
        {
          title: 'مطابقة الأرقام',
          body: 'المدفوع، المتبقي، الأوفر، وتكلفة التنازل.',
        },
        {
          title: 'حفظ حق البروكر',
          body: 'العمولة تتسجل وتبقى مرتبطة بحالة الإغلاق.',
        },
      ],
    },
    testimonials: {
      eyebrow: 'آراء',
      title: 'ناس خرجت من اللخبطة بوضوح',
      items: [
        { imageKey: safqaAssetKeys.personOne, quote: 'كنت داخل على إلغاء وخسارة، صفقة رتبت الورق وخلت الطريق واضح.', name: 'أحمد سامي', role: 'مالك وحدة' },
        { imageKey: safqaAssetKeys.personTwo, quote: 'اشتريت بسعر تعاقد قديم وكل رقم كان عليه مستند.', name: 'منى خالد', role: 'مشتري فرصة' },
        { imageKey: safqaAssetKeys.personThree, quote: 'سجلت عقد عميلي وفضلت متابع العمولة خطوة بخطوة.', name: 'كريم عادل', role: 'بروكر فريلانسر' },
      ],
    },
    cta: {
      title: 'جاهز تبدأ صفقة موثقة؟',
      body: 'سواء عايز تبيع، تشتري، أو تقفل عقد كبروكر، نبدأ بمراجعة الورق الأول.',
      primary: 'ابدأ الآن',
      secondary: 'تواصل معنا',
    },
    footer: {
      title: 'صفقة',
      body: 'منصة لتوثيق التنازل وإغلاق صفقات البروكرز.',
      phone: '+20 100 000 0000',
      email: 'hello@safqa.realestate',
    },
    sellersPage: {
      title: 'عايز تخرج من تعاقدك؟ خليها بحساب',
      subtitle: 'قبل أي خطوة، لازم تعرف موقفك بالظبط: خصم الإلغاء، جدول الاسترداد، وقيمة اللي ممكن تسترجعه بنقل التعاقد. ده بالظبط اللي بيعمله تقرير الخروج — مجانًا. ومفيش أي عمولة عليك كبايع لو بعت من خلالنا.',
      points: [
        'مراجعة حقيقية لعقدك ومستنداتك — مش حسبة تقريبية',
        'مقارنة موثقة: الإلغاء مقابل نقل التعاقد',
        'توصية واضحة بأفضل طريق — حتى لو كان الاستمرار',
        'مجانًا تمامًا: مفيش عمولة على البايع — المشتري هو اللي بيدفع 1.25%',
      ],
      ownersOnlyTitle: 'بنتعامل مع مالك الوحدة نفسه بس',
      ownersOnlyDesc: 'الطلبات اللي بتيجي من سماسرة أو وسطاء بنستبعدها، وأي وحدة يتبيّن إنها من وسيط بنرفضها. سبب المنصة الأساسي إن المشتري ياخد سعر التعاقد القديم من غير أوفر.',
      form: {
        stepOf: 'خطوة {current} من {total}',
        step1Title: 'بيانات الوحدة',
        step2Title: 'تفاصيل الأقساط والوحدة',
        step3Title: 'بيانات التواصل والتحقق',
        developerName: 'اسم المطور',
        projectName: 'اسم المشروع / الكمبوند',
        totalPrice: 'إجمالي سعر الوحدة في العقد',
        amountPaid: 'إجمالي اللي دفعته لحد النهارده',
        currentPrice: 'سعر نفس الوحدة من المطور النهارده (اختياري)',
        currentPriceHint: 'بنخدمه نحسب للمشتري هيوفر كام — لو مش متأكد سيبه فاضي',
        zeroOverAck: 'أؤكد إني فاهم إن المبلغ اللي هستلمه هو اللي دفعته بالظبط — بدون أي أوفر أو زيادة.',
        remainingPrice: 'إجمالي المبلغ المتبقي للمطور',
        nextInstallment: 'قيمة القسط القادم',
        frequency: 'نظام القسط',
        freqMonthly: 'شهري',
        freqQuarterly: 'ربع سنوي (كل 3 شهور)',
        freqSemiannual: 'نصف سنوي',
        freqAnnual: 'سنوي',
        unitType: 'نوع الوحدة',
        typeApartment: 'شقة',
        typeVilla: 'فيلا مستقلة',
        typeTownhouse: 'تاون هاوس',
        typeTwinhouse: 'توين هاوس',
        typeDuplex: 'دوبلكس',
        typePenthouse: 'بنتهاوس',
        typeChalet: 'شاليه',
        typeLand: 'أرض',
        typeRetail: 'محل تجاري',
        typeClinic: 'عيادة طبية',
        typeOffice: 'مكتب إداري',
        location: 'المنطقة / الموقع',
        area: 'المساحة (م²)',
        gardenArea: 'مساحة الجاردن (م²) (اختياري)',
        floor: 'الدور / الطابق',
        bedrooms: 'عدد الغرف',
        bathrooms: 'عدد الحمامات',
        finishingType: 'نوع التشطيب',
        finishingCoreShell: 'طوب أحمر / بدون تشطيب',
        finishingSemi: 'نصف تشطيب',
        finishingFully: 'كامل التشطيب',
        finishingFurnished: 'متشطبة بالفرش',
        deliveryStatus: 'حالة الاستلام',
        deliveryReady: 'جاهزة للاستلام',
        deliveryUnderConst: 'تحت الإنشاء',
        description: 'وصف مختصر للوحدة (اكتب تفاصيل إضافية مثل الفيو، مميزات خاصة، إلخ)',
        amenitiesLabel: 'المميزات الإضافية',
        amenityPool: 'حمام سباحة',
        amenityGarden: 'جاردن خاصة',
        amenityRoof: 'رووف',
        amenitySecurity: 'أمن 24 ساعة',
        amenityClub: 'كلوب هاوس',
        amenityGarage: 'جراج',
        amenityElevator: 'مصعد',
        amenityServices: 'قريبة من الخدمات',
        contractYear: 'سنة التعاقد',
        nextInstallmentDate: 'تاريخ القسط القادم',
        maintenancePaid: 'تم سداد وديعة الصيانة (بالكامل أو جزء منها)',
        maintenanceAmount: 'قيمة وديعة الصيانة المسددة',
        uploadContract: 'صورة العقد / جدول الأقساط',
        uploadReceipts: 'إيصالات السداد الأخيرة (اختياري)',
        uploadHint: 'اسحب وأفلت الملف هنا أو اضغط للتصفح (PDF أو صور)',
        locNewCairo: 'القاهرة الجديدة',
        locZayed: 'الشيخ زايد',
        locOctober: '6 أكتوبر',
        locShorouk: 'الشروق',
        locMostakbal: 'مستقبل سيتي',
        locCapital: 'العاصمة الإدارية',
        locNorthCoast: 'الساحل الشمالي',
        locSokhna: 'العين السخنة',
        locOther: 'منطقة أخرى',
        name: 'الاسم بالكامل',
        phone: 'رقم الموبايل (واتساب)',
        email: 'البريد الإلكتروني (اختياري)',
        ownerConfirm: 'أقر إني مالك الوحدة نفسي، ولست وسيطًا عقاريًا.',
        nextBtn: 'كمّل',
        backBtn: 'ارجع',
        submitBtn: 'إرسال الطلب للمراجعة',
        successTitle: 'وصلنا طلبك بنجاح ✓',
        successSubtitle: 'هنراجع بياناتك ونتواصل معاك خلال ساعات العمل — عادةً في نفس اليوم.',
        whatsappCta: 'عايز رد أسرع؟ ابعتلنا على واتساب',
        backHome: 'الرجوع للرئيسية',
      },
      auth: {
        loginTab: 'تسجيل الدخول',
        registerTab: 'إنشاء حساب جديد',
        loginTitle: 'مرحبًا بك في صفقة',
        registerTitle: 'ابدأ بيع وحدتك الآن',
        password: 'كلمة المرور',
        confirmPassword: 'تأكيد كلمة المرور',
        loginBtn: 'تسجيل الدخول',
        registerBtn: 'إنشاء حساب',
        noAccount: 'ليس لديك حساب؟ سجل الآن',
        haveAccount: 'لديك حساب بالفعل؟ سجل دخولك',
        benefitsTitle: 'ليه تبيع وحدتك مع صفقة؟',
        benefit1: '0% عمولة على عملية البيع بالكامل.',
        benefit2: 'تواصل مباشر مع مشترين جادين وموثقين.',
        benefit3: 'سرية تامة وحماية لبيانات عقارك ومستنداتك.',
      }
    },
  },
  en: {
    brand: 'Safqa',
    switchLanguage: 'Arabic',
    nav: {
      home: 'Home',
      decision: 'Quick Decision',
      paths: 'Who Benefits',
      opportunities: 'Opportunities',
      howItWorks: 'How We Work',
      process: 'Transfer Journey',
      brokers: 'For Brokers',
    },
    hero: {
      eyebrow: 'Property transfer platform — no overprice',
      title: 'Safqa for property transfer deals',
      body: 'The seller recovers every pound paid in cash. The buyer gets the old contract price. Every number is document-verified.',
      primaryCta: 'Sell your unit',
      secondaryCta: 'View buy deals',
      proofLabel: 'Every number',
      proofValue: 'documented',
      heroCard: {
        cancelTitle: 'If he cancels with the developer',
        cancelDeductLabel: 'Cancellation deduction (15% of total unit price)',
        cancelDeductValue: '- 1,500,000 EGP',
        cancelGetLabel: 'What he gets back',
        cancelGetValue: '500,000 EGP',
        cancelYearsLabel: 'Paid over',
        cancelYearsValue: '3 years',
        cancelNote: '75% loss + years of waiting',
        vsLabel: 'VS',
        transferTitle: 'If he transfers via Safqa',
        transferGetLabel: 'He recovers what he paid',
        transferGetValue: '2,000,000 EGP',
        transferGetSub: 'Cash upon transfer completion',
        transferNote: 'Full money back. Buyer wins old price.',
      },
    },
    search: {
      title: 'Find a verified opportunity',
      location: 'Location or compound',
      type: 'Unit type',
      status: 'Deal status',
      submit: 'Search',
    },
    stats: [
      { value: '305+', label: 'files reviewed' },
      { value: '1090+', label: 'indexed opportunities' },
      { value: '67', label: 'partner brokers' },
      { value: '15%', label: 'avoidable cancellation loss' },
    ],
    sellerBuyer: {
      eyebrow: 'Who benefits?',
      title: 'One needs to sell, one is waiting for the deal — we connect them',
      subtitle: "This isn't regular resale: zero overprice. The seller gets exactly what they paid. The buyer gets the old contract price as-is.",
      seller: {
        tag: 'Seller — unit owner',
        title: 'No overprice = fastest sale in the market',
        body: 'Because your price is exactly what you paid with zero markup, your unit becomes the most attractive opportunity for buyers — and sells faster. You recover your full investment in cash instead of the developer deducting and installmenting your refund over years.',
        features: [
          'Recover 100% of what you paid — cash upon transfer completion',
          'No public ads, no broker calls',
          'We prepare your transfer file and follow up step by step until signing',
        ],
        freeNote: 'Completely free for you — Safqa charges zero commission from the seller.',
        cta: 'List your unit for transfer',
      },
      buyer: {
        tag: 'Buyer',
        title: 'An installment unit without paying overprice to anyone',
        body: 'You get the unit at its old contract price — significantly below today\'s market — and continue the regular installments. That difference is your profit from the day you sign.',
        features: [
          'Old contract price as-is — overprice is prohibited on the platform',
          'Contract, payments, and remaining balance all verified before you see the deal',
          'Official transfer approved by the developer — no proxy letters',
        ],
        cta: 'View available deals',
      },
    },
    comparison: {
      eyebrow: 'The real difference',
      title: 'How do we differ from regular resale?',
      subtitle: "The market is full of ads and brokers — we operate very differently",
      rows: [
        { label: 'Price', regular: 'Overprice on top, inflated for negotiation', safqa: 'No overprice — price = what was actually paid, documented with receipts' },
        { label: 'Numbers', regular: "Seller and broker's word with no evidence", safqa: 'Contract, payments, and remaining balance verified with official documents' },
        { label: 'Process', regular: "Broker connects you then you're on your own", safqa: 'We walk with you through every transfer step until signing and collection' },
        { label: 'Commission', regular: 'Brokerage from both sides at every step, surprises included', safqa: 'Free for seller — 1.25% from buyer only, upon transfer completion' },
      ],
    },
    numbersExample: {
      eyebrow: 'Real example',
      title: 'Numbers example',
      subtitle: 'Unit total price 10M EGP. Owner paid 2M over 3 years and stopped payments.',
      cancelCard: {
        title: 'If he cancels with the developer',
        deductLabel: 'Cancellation deduction (15% of total)',
        deductValue: '- 1,500,000 EGP',
        getLabel: 'What he gets back',
        getValue: '500,000 EGP',
        yearsLabel: 'Paid over',
        yearsValue: '3 years',
        note: '75% loss + years of waiting',
      },
      transferCard: {
        title: 'If he transfers via Safqa',
        getLabel: 'He recovers what he paid',
        getValue: '2,000,000 EGP',
        getSub: 'Cash upon transfer completion',
        feeLabel: "Safqa's commission from seller",
        feeValue: 'Zero',
        feeSub: 'Pays nothing — receives full amount',
        note: 'Full money back. Buyer wins old price.',
      },
      disclaimer: "These numbers are illustrative. Deduction rates and recovery terms vary per contract — that's exactly what we review in the free exit report.",
    },
    paths: {
      eyebrow: 'Paths',
      title: 'Three problems, one clear solution',
      items: [
        {
          title: 'Distressed owner',
          body: 'List your unit for transfer with verified numbers instead of losing money through cancellation.',
          action: 'Value my unit',
        },
        {
          title: 'Opportunity buyer',
          body: 'Buy at an older contract price below today market and continue the installments clearly.',
          action: 'View units',
        },
        {
          title: 'Freelance broker',
          body: 'Register the contract, let Safqa close it, and track your commission in one place.',
          action: 'Register contract',
        },
      ],
    },
    howItWorks: {
      eyebrow: 'How we work',
      title: 'How do we work?',
      subtitle: 'Five clear steps, with a case manager by your side at every step',
      steps: [
        { title: 'Assess your contract', body: 'Enter your contract details and know your situation for free — once you submit, your account is set up automatically' },
        { title: 'Upload your documents', body: 'Contract and payment receipts — we review and verify them' },
        { title: 'We prepare your deal', body: 'We verify numbers with documents and prepare a trusted listing for buyers' },
        { title: 'We find the buyer', body: 'We match your unit with buyers who can genuinely continue the payments' },
        { title: 'Contract transfer', body: 'We walk with you through transfer procedures step by step until you collect' },
      ],
    },
    fairExit: {
      eyebrow: 'Our principles',
      title: 'Fair exit standards',
      subtitle: 'We set binding rules for ourselves before asking for your trust',
      items: [
        { title: 'Every number has a source', body: "We show you what's confirmed by documents vs. what's estimated — no misleading promises" },
        { title: 'Completely free for sellers', body: 'Zero commission from the seller. The buyer pays 1.25% only upon transfer completion — no hidden fees' },
        { title: 'Your privacy is protected', body: 'You can choose the silent exit — no public listing, no annoying calls' },
        { title: 'Zero pressure', body: "We present all your options — even if the best choice for you is to continue your contract" },
      ],
    },
    calculatorCta: {
      title: 'Know your situation in one minute',
      subtitle: 'Enter the unit price and what you paid, and see the difference between cancellation and transfer',
      cta: 'Calculate now',
    },
    dualCta: {
      seller: {
        title: "Can't continue your installments?",
        body: "Don't rush into a cancellation decision. Know your situation first — the assessment is free with no obligation.",
        cta: 'Start contract assessment',
      },
      buyer: {
        title: 'Looking for a real opportunity?',
        body: 'Register your budget and we\'ll send you deals that match your available cash and comfortable installment.',
        cta: 'Register as buyer',
      },
    },
    opportunities: {
      eyebrow: 'Selected offers',
      title: 'Transfer opportunities ready for review',
      items: [
        {
          id: 'unit-1',
          imageKey: safqaAssetKeys.propertyOne,
          gallery: [safqaAssetKeys.propertyOne, safqaAssetKeys.propertyTwo, safqaAssetKeys.listingOne],
          title: 'Unit ready for transfer',
          location: 'New Cairo',
          price: '3,950,000',
          oldPrice: '4,800,000',
          meta: '145 m2 / Apartment',
          badge: 'Documents verified',
          type: 'apartment',
          description: 'Distinctive residential apartment in a strategic location in New Cairo, modern design with a panoramic view, close to all amenities.',
          amenities: ['24/7 Security', 'Swimming Pool', 'Private Parking', 'Health Club'],
          bedrooms: '3',
          bathrooms: '2',
          remainingPrice: '1,850,000',
          installment: '120,000',
          frequency: 'Quarterly',
          deliveryYear: '2026',
          unitCode: 'U-11311',
          developer: 'Emaar Misr',
          project: 'Mivida',
          floor: '1st Floor',
          contractYear: '2023',
          marketPrice: '7,500,000',
          meterPrice: '27,241',
        },
        {
          id: 'unit-2',
          imageKey: safqaAssetKeys.propertyTwo,
          gallery: [safqaAssetKeys.propertyTwo, safqaAssetKeys.listingTwo, safqaAssetKeys.propertyFour],
          title: 'Below market price opportunity',
          location: 'Sheikh Zayed',
          price: '5,100,000',
          oldPrice: '6,200,000',
          meta: '210 m2 / Townhouse',
          badge: 'Under Review',
          type: 'townhouse',
          description: 'Spacious townhouse in the heart of Sheikh Zayed, featuring a private garden in a quiet, family-friendly location.',
          amenities: ['Private Garden', 'Kids Play Area', 'Sports Club'],
          bedrooms: '4',
          bathrooms: '3',
          remainingPrice: '3,200,000',
          installment: '200,000',
          frequency: 'Quarterly',
          deliveryYear: '2027',
          unitCode: 'U-11312',
          developer: 'SODIC',
          project: 'Villette',
          floor: 'Ground with Garden',
          contractYear: '2024',
          marketPrice: '9,800,000',
          meterPrice: '24,285',
        },
        {
          id: 'unit-3',
          imageKey: safqaAssetKeys.propertyThree,
          gallery: [safqaAssetKeys.propertyThree, safqaAssetKeys.propertyOne, safqaAssetKeys.listingThree],
          title: 'Closable broker contract',
          location: 'New Capital',
          price: '2,850,000',
          oldPrice: '3,400,000',
          meta: '118 m2 / Apartment',
          badge: 'Commission saved',
          type: 'apartment',
          description: 'Luxury apartment in the New Administrative Capital, a great investment opportunity with flexible payment plans.',
          amenities: ['Smart Home', 'Gym', 'Spa'],
          bedrooms: '2',
          bathrooms: '2',
          remainingPrice: '1,450,000',
          installment: '95,000',
          frequency: 'Quarterly',
          deliveryYear: '2026',
          unitCode: 'U-11313',
          developer: 'Talaat Moustafa',
          project: 'Celia',
          floor: '2nd Floor',
          contractYear: '2023',
          marketPrice: '4,900,000',
          meterPrice: '24,152',
        },
        {
          id: 'unit-4',
          imageKey: safqaAssetKeys.propertyFour,
          gallery: [safqaAssetKeys.propertyFour, safqaAssetKeys.listingOne, safqaAssetKeys.propertyTwo],
          title: 'Sea view chalet for transfer',
          location: 'North Coast',
          price: '6,200,000',
          oldPrice: '7,800,000',
          meta: '130 m2 / Chalet',
          badge: 'Confirmed seriousness',
          type: 'chalet',
          description: 'Luxury chalet directly overlooking the sea in the North Coast, within a fully serviced resort.',
          amenities: ['Sea View', 'Aqua Park', 'Restaurants & Cafes'],
          bedrooms: '3',
          bathrooms: '2',
          remainingPrice: '4,500,000',
          installment: '310,000',
          frequency: 'Quarterly',
          deliveryYear: '2027',
          unitCode: 'U-11314',
          developer: 'Tatweer Misr',
          project: 'Salt',
          floor: '1st Floor',
          contractYear: '2024',
          marketPrice: '12,500,000',
          meterPrice: '47,692',
        },
        {
          id: 'unit-5',
          imageKey: safqaAssetKeys.listingOne,
          gallery: [safqaAssetKeys.listingOne, safqaAssetKeys.propertyThree, safqaAssetKeys.listingTwo],
          title: 'Fully finished apartment instant delivery',
          location: '6th of October',
          price: '3,100,000',
          oldPrice: '3,800,000',
          meta: '155 m2 / Apartment',
          badge: 'Documents verified',
          type: 'apartment',
          description: 'Ultra super lux finished apartment ready for immediate move-in in an upscale neighborhood in 6th of October.',
          amenities: ['Fully Finished', 'Elevator', 'Security'],
          bedrooms: '3',
          bathrooms: '3',
          remainingPrice: '1,200,000',
          installment: '80,000',
          frequency: 'Quarterly',
          deliveryYear: '2025',
          unitCode: 'U-11315',
          developer: 'Orascom',
          project: 'O West',
          floor: '3rd Floor',
          contractYear: '2022',
          marketPrice: '5,500,000',
          meterPrice: '20,000',
        },
        {
          id: 'unit-6',
          imageKey: safqaAssetKeys.listingTwo,
          gallery: [safqaAssetKeys.listingTwo, safqaAssetKeys.propertyFour, safqaAssetKeys.listingThree],
          title: 'Twinhouse with easy installments',
          location: 'Sheikh Zayed',
          price: '8,500,000',
          oldPrice: '10,500,000',
          meta: '280 m2 / Twinhouse',
          badge: 'Confirmed seriousness',
          type: 'twinhouse',
          description: 'Luxurious twinhouse with modern design, offering vast spaces and complete comfort with highly flexible payments.',
          amenities: ['Green Areas', 'BBQ Area', '2-Car Garage'],
          bedrooms: '5',
          bathrooms: '4',
          remainingPrice: '5,600,000',
          installment: '350,000',
          frequency: 'Quarterly',
          deliveryYear: '2028',
          unitCode: 'U-11316',
          developer: 'Emaar Misr',
          project: 'Cairo Gate',
          floor: 'Ground with Garden',
          contractYear: '2024',
          marketPrice: '16,500,000',
          meterPrice: '30,357',
        },
        {
          id: 'unit-7',
          imageKey: safqaAssetKeys.listingThree,
          gallery: [safqaAssetKeys.listingThree, safqaAssetKeys.propertyOne, safqaAssetKeys.listingOne],
          title: 'Standalone villa lowest downpayment',
          location: 'New Cairo',
          price: '11,200,000',
          oldPrice: '13,500,000',
          meta: '360 m2 / Villa',
          badge: 'Under Review',
          type: 'villa',
          description: 'Standalone villa with vast spaces in one of New Cairo’s finest compounds. Enjoy absolute privacy and luxury.',
          amenities: ['Private Pool', 'Maid Room', 'Large Garden', 'Smart Home'],
          bedrooms: '6',
          bathrooms: '5',
          remainingPrice: '6,800,000',
          installment: '450,000',
          frequency: 'Quarterly',
          deliveryYear: '2027',
          unitCode: 'U-11317',
          developer: 'Mountain View',
          project: 'iCity',
          floor: 'Ground Standalone',
          contractYear: '2023',
          marketPrice: '22,000,000',
          meterPrice: '31,111',
        },
        {
          id: 'unit-8',
          imageKey: safqaAssetKeys.propertyOne,
          gallery: [safqaAssetKeys.propertyOne, safqaAssetKeys.listingTwo, safqaAssetKeys.propertyThree],
          title: 'Chalet in fully serviced resort',
          location: 'Ain Sokhna',
          price: '2,400,000',
          oldPrice: '3,100,000',
          meta: '95 m2 / Chalet',
          badge: 'Commission saved',
          type: 'chalet',
          description: 'Gorgeous summer chalet in Ain Sokhna with full hotel services, perfect for short family vacations.',
          amenities: ['Hotel Services', 'Private Beach', 'Kids Area'],
          bedrooms: '2',
          bathrooms: '1',
          remainingPrice: '1,100,000',
          installment: '75,000',
          frequency: 'Quarterly',
          deliveryYear: '2026',
          unitCode: 'U-11318',
          developer: 'Arab Developers',
          project: 'Porto Sokhna',
          floor: '2nd Floor',
          contractYear: '2023',
          marketPrice: '4,200,000',
          meterPrice: '25,263',
        }
      ],
    },
    process: {
      eyebrow: 'Transfer journey',
      title: 'Clear steps until completion',
      body: 'From contract review to signature and commission payout.',
      items: [
        { title: 'Document audit', body: 'Contract, receipts, and installment schedule.' },
        { title: 'Number confirmation', body: 'Paid amount, remaining balance, and transfer costs.' },
        { title: 'Closing', body: 'Follow signature and deal status through completion.' },
      ],
    },
    broker: {
      eyebrow: 'For brokers',
      title: 'Bring the deal, we close it',
      body: 'The independent broker enters the contract, follows the status, and sees commission progress clearly.',
      cards: [
        { value: '24h', label: 'initial review' },
        { value: '9d', label: 'average closing' },
        { value: '100%', label: 'tracked status' },
      ],
    },
    command: {
      eyebrow: 'Deal command room',
      title: 'One live view for every contract',
      body: 'Client, unit, paid amount, remaining balance, documents, and transfer status in one operational screen.',
      metrics: [
        { value: '43', label: 'files under audit' },
        { value: '28', label: 'transfer actions' },
        { value: 'EGP 620K', label: 'payouts pending' },
      ],
      queue: [
        { title: 'East Residence A-1407', meta: 'Broker contract / 5.8M', status: 'Review' },
        { title: 'West Park T-22', meta: 'Transfer / 9.4M', status: 'Booking' },
        { title: 'Capital Line B-08', meta: 'Buyer opportunity / 4.1M', status: 'Ready' },
      ],
    },
    guarantees: {
      eyebrow: 'Verification',
      title: 'No number without a document',
      items: [
        {
          title: 'Contract audit',
          body: 'We review cancellation, transfer terms, and any possible penalties.',
        },
        {
          title: 'Number matching',
          body: 'Paid amount, remaining balance, overprice, and transfer costs.',
        },
        {
          title: 'Broker rights',
          body: 'Commission is registered and tied to the closing status.',
        },
      ],
    },
    testimonials: {
      eyebrow: 'Reviews',
      title: 'People who moved from confusion to clarity',
      items: [
        {
          imageKey: safqaAssetKeys.personOne,
          quote: 'I was heading toward cancellation and a loss. Safqa organized the documents and made the path clear.',
          name: 'Ahmed Samy',
          role: 'Unit owner',
        },
        {
          imageKey: safqaAssetKeys.personTwo,
          quote: 'I bought at an older contract price, and every number had a document behind it.',
          name: 'Mona Khaled',
          role: 'Opportunity buyer',
        },
        {
          imageKey: safqaAssetKeys.personThree,
          quote: 'I registered my client contract and tracked commission status step by step.',
          name: 'Karim Adel',
          role: 'Freelance broker',
        },
      ],
    },
    cta: {
      title: 'Ready to start a documented deal?',
      body: 'Whether you want to sell, buy, or close a contract as a broker, the first step is a clean document review.',
      primary: 'Start now',
      secondary: 'Contact us',
    },
    footer: {
      title: 'Safqa',
      body: 'A platform for documented transfers and broker deal closing.',
      phone: '+20 100 000 0000',
      email: 'hello@safqa.realestate',
    },
    sellersPage: {
      title: 'Want to Exit Your Contract? Do It with Calculations',
      subtitle: 'Before taking any step, you must know your exact position: cancellation fee, refund schedule, and what you can recover by transferring. That is exactly what our Exit Report does — for free. And there is zero commission on you as a seller.',
      points: [
        'A real review of your contract and documents — not an estimate',
        'Documented comparison: cancellation vs contract transfer',
        'A clear recommendation on the best path — even if it is to continue',
        '100% Free: No commission on the seller — the buyer pays 1.25%',
      ],
      ownersOnlyTitle: 'We deal with the unit owner only',
      ownersOnlyDesc: 'We exclude requests from brokers. The primary goal of Safqa is for buyers to get the old contract price without any overprice markup.',
      form: {
        stepOf: 'Step {current} of {total}',
        step1Title: 'Unit Details',
        step2Title: 'Installments & Unit Info',
        step3Title: 'Contact & Verification',
        developerName: 'Developer Name',
        projectName: 'Project / Compound Name',
        totalPrice: 'Total Price in Contract',
        amountPaid: 'Total Paid until Today',
        currentPrice: 'Current Developer Price Today (Optional)',
        currentPriceHint: 'Used to calculate buyer savings — leave empty if unsure',
        zeroOverAck: 'I confirm that I understand I will receive exactly what I paid — without any overprice or markup.',
        remainingPrice: 'Remaining Amount for Developer',
        nextInstallment: 'Next Installment Amount',
        frequency: 'Installment Frequency',
        freqMonthly: 'Monthly',
        freqQuarterly: 'Quarterly',
        freqSemiannual: 'Semi-annual',
        freqAnnual: 'Annual',
        unitType: 'Unit Type',
        typeApartment: 'Apartment',
        typeVilla: 'Standalone Villa',
        typeTownhouse: 'Townhouse',
        typeTwinhouse: 'Twin House',
        typeDuplex: 'Duplex',
        typePenthouse: 'Penthouse',
        typeChalet: 'Chalet',
        typeLand: 'Land',
        typeRetail: 'Retail Shop',
        typeClinic: 'Medical Clinic',
        typeOffice: 'Administrative Office',
        location: 'Region / Location',
        area: 'Area (sqm)',
        gardenArea: 'Garden Area (sqm) (Optional)',
        floor: 'Floor / Level',
        bedrooms: 'Bedrooms',
        bathrooms: 'Bathrooms',
        finishingType: 'Finishing Type',
        finishingCoreShell: 'Core & Shell / Unfinished',
        finishingSemi: 'Semi-finished',
        finishingFully: 'Fully Finished',
        finishingFurnished: 'Furnished',
        deliveryStatus: 'Delivery Status',
        deliveryReady: 'Ready to Move / Delivered',
        deliveryUnderConst: 'Under Construction',
        description: 'Brief Unit Description (Add details like view, layout, specs)',
        amenitiesLabel: 'Additional Amenities',
        amenityPool: 'Swimming Pool',
        amenityGarden: 'Private Garden',
        amenityRoof: 'Roof',
        amenitySecurity: '24h Security',
        amenityClub: 'Club House',
        amenityGarage: 'Garage',
        amenityElevator: 'Elevator',
        amenityServices: 'Close to Services',
        contractYear: 'Contract Year',
        nextInstallmentDate: 'Next Installment Date',
        maintenancePaid: 'Maintenance deposit paid (Fully or partially)',
        maintenanceAmount: 'Paid Maintenance Amount',
        uploadContract: 'Contract Copy / Installment Schedule',
        uploadReceipts: 'Recent Payment Receipts (Optional)',
        uploadHint: 'Drag & drop file here or click to browse (PDF or images)',
        locNewCairo: 'New Cairo',
        locZayed: 'Sheikh Zayed',
        locOctober: '6 October',
        locShorouk: 'Shorouk',
        locMostakbal: 'Mostakbal City',
        locCapital: 'New Capital',
        locNorthCoast: 'North Coast',
        locSokhna: 'Ain Sokhna',
        locOther: 'Other Region',
        name: 'Full Name',
        phone: 'Mobile Number (WhatsApp)',
        email: 'Email Address (Optional)',
        ownerConfirm: 'I confirm that I am the actual unit owner and not a broker.',
        nextBtn: 'Continue',
        backBtn: 'Back',
        submitBtn: 'Submit Request for Review',
        successTitle: 'Request Received Successfully ✓',
        successSubtitle: 'We will review your details and contact you during working hours — usually same day.',
        whatsappCta: 'Want a faster response? Contact us on WhatsApp',
        backHome: 'Back to Home',
      },
      auth: {
        loginTab: 'Login',
        registerTab: 'Register New Account',
        loginTitle: 'Welcome to Safqa',
        registerTitle: 'Start Selling Your Unit Now',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        loginBtn: 'Login',
        registerBtn: 'Create Account',
        noAccount: "Don't have an account? Register now",
        haveAccount: 'Already have an account? Login here',
        benefitsTitle: 'Why Sell Your Unit With Safqa?',
        benefit1: '0% commission on the entire transaction.',
        benefit2: 'Direct communication with verified, serious buyers.',
        benefit3: 'Total confidentiality and protection for your property documents.',
      }
    },
  },
}
