import { safqaAssetKeys } from '../../config/safqaAssets'
import type { Locale, SafqaLandingCopy } from './safqaLandingTypes'

export const safqaLandingCopy: Record<Locale, SafqaLandingCopy> = {
  ar: {
    brand: 'صفقة',
    switchLanguage: 'English',
    nav: {
      home: 'الرئيسية',
      paths: 'المسارات',
      opportunities: 'الفرص',
      process: 'التنازل',
      brokers: 'للبروكرز',
    },
    hero: {
      eyebrow: 'منصة التنازل عن وحدات التقسيط — بدون أوفر',
      title: 'صفقة للتنازل العقاري',
      body: 'البايع يسترجع كل اللي دفعه كاش، والمشتري ياخد سعر التعاقد القديم. كل الأرقام متحققة بالمستندات.',
      primaryCta: 'بيع وحدتك',
      secondaryCta: 'شوف فرص الشراء',
      proofLabel: 'كل رقم',
      proofValue: 'بمستند',
      heroCard: {
        cancelTitle: 'لو رجّع الوحدة للمطور',
        cancelDeductLabel: 'خصم الإلغاء (15% من سعر الوحدة كله)',
        cancelDeductValue: '- 1,500,000 ج.م',
        cancelGetLabel: 'اللي هيرجعله',
        cancelGetValue: '500,000 ج.م',
        cancelYearsLabel: 'ياخدها على',
        cancelYearsValue: '3 سنين',
        cancelNote: 'خسارة 75% من فلوسه + سنين انتظار',
        vsLabel: 'VS',
        transferTitle: 'لو نقل تعاقده عن طريق صفقة',
        transferGetLabel: 'يسترجع اللي دفعه',
        transferGetValue: '2,000,000 ج.م',
        transferGetSub: 'كاش عند إتمام النقل',
        transferNote: 'فلوسه كاملة، والمشتري كسب سعر قديم',
      },
    },
    search: {
      title: 'دور على فرصة موثقة',
      location: 'الموقع أو الكمبوند',
      type: 'نوع الوحدة',
      status: 'حالة الصفقة',
      submit: 'ابحث',
    },
    stats: [
      { value: '305+', label: 'ملف تمت مراجعته' },
      { value: '1090+', label: 'فرصة مفهرسة' },
      { value: '67', label: 'بروكر متعاون' },
      { value: '15%', label: 'خسارة ممكن تتجنبها' },
    ],
    sellerBuyer: {
      eyebrow: 'مين المستفيد؟',
      title: 'طرف محتاج يبيع، وطرف مستني الفرصة — وإحنا بنوصّلهم',
      subtitle: 'ده مش ريسيل عادي: مفيش أوفر خالص. البايع بياخد اللي دفعه بالظبط، والمشتري بياخد سعر التعاقد القديم زي ما هو',
      seller: {
        tag: 'البايع — صاحب الوحدة',
        title: 'بدون أوفر = أسرع بيع في السوق',
        body: 'لأن سعرك هو نفس اللي دفعته من غير أي زيادة، وحدتك بتبقى أحسن فرصة قدام المشترين — فبتتباع أسرع. تسترجع فلوسك كاملة كاش، بدل ما المطور يخصم منك ويقسّط لك الباقي على سنين.',
        features: [
          'تسترجع 100% من اللي دفعته — كاش عند إتمام التنازل',
          'من غير إعلانات علنية ولا تليفونات سماسرة',
          'بنجهّز معاك ملف التنازل ونتابع معاك خطوة بخطوة لحد الإمضاء',
        ],
        freeNote: 'مجانًا عليك تمامًا — صفقة مش بتاخد أي عمولة من البايع.',
        cta: 'اعرض وحدتك للتنازل',
      },
      buyer: {
        tag: 'المشتري',
        title: 'وحدة بالتقسيط من غير ما تدفع أوفر لحد',
        body: 'بتاخد الوحدة بسعر تعاقدها القديم — أرخص من سعر المطور النهارده بفرق كبير — وتكمّل الأقساط العادية. الفرق ده مكسبك من يوم ما تمضي.',
        features: [
          'سعر التعاقد القديم زي ما هو — الأوفر ممنوع على المنصة',
          'العقد والمدفوعات والمتبقي متحقق منهم قبل ما تشوف الفرصة',
          'تنازل رسمي معتمد من المطور — مش توكيلات وكلام',
        ],
        cta: 'شوف الفرص المتاحة',
      },
    },
    comparison: {
      eyebrow: 'الفرق الحقيقي',
      title: 'إيه الفرق بيننا وبين الريسيل العادي؟',
      subtitle: 'السوق مليان إعلانات وسماسرة — إحنا بنشتغل بطريقة تانية خالص',
      rows: [
        { label: 'السعر', regular: 'أوفر فوق السعر، ومبالغة عشان الفصال', safqa: 'بدون أوفر — السعر = اللي اتدفع فعلًا، موثق بالإيصالات' },
        { label: 'الأرقام', regular: 'كلام البايع والسمسار من غير دليل', safqa: 'متحققين من العقد والمدفوعات والمتبقي — بالمستندات الرسمية' },
        { label: 'الإجراءات', regular: 'السمسار بيوصّلك وبعدين انت وحظك', safqa: 'بنمشي معاك في كل خطوات التنازل لحد الإمضاء والقبض' },
        { label: 'العمولة', regular: 'سعي وسمسرة من الطرفين في كل خطوة ومفاجآت', safqa: 'مجانًا للبايع — 1.25% على المشتري بس، وعند إتمام التنازل فقط' },
      ],
    },
    numbersExample: {
      eyebrow: 'مثال حقيقي',
      title: 'مثال بالأرقام',
      subtitle: 'وحدة سعرها الإجمالي 10 مليون جنيه، صاحبها دفع منها 2 مليون على 3 سنين وموقف عن السداد',
      cancelCard: {
        title: 'لو رجّع الوحدة للمطور',
        deductLabel: 'خصم الإلغاء (15% من سعر الوحدة كله)',
        deductValue: '- 1,500,000 ج.م',
        getLabel: 'اللي هيرجعله',
        getValue: '500,000 ج.م',
        yearsLabel: 'ياخدها على',
        yearsValue: '3 سنين',
        note: 'خسارة 75% من فلوسه + سنين انتظار',
      },
      transferCard: {
        title: 'لو نقل تعاقده عن طريق صفقة',
        getLabel: 'يسترجع اللي دفعه',
        getValue: '2,000,000 ج.م',
        getSub: 'كاش عند إتمام النقل',
        feeLabel: 'عمولة صفقة عليك كبايع',
        feeValue: 'صفر',
        feeSub: 'تدفع صفر — تستلم اللي دفعته بالكامل',
        note: 'فلوسه كاملة، والمشتري كسب سعر قديم',
      },
      disclaimer: 'الأرقام دي مثال توضيحي. نسبة الخصم وشروط الاسترداد بتختلف من عقد لعقد — وده بالظبط اللي بنراجعه في تقرير الخروج المجاني.',
    },
    paths: {
      eyebrow: 'المسارات',
      title: 'ثلاث مشاكل وحل واحد واضح',
      items: [
        {
          title: 'مالك متعثر',
          body: 'بدل ما تلغي العقد وتخسر، اعرض وحدتك للتنازل بأرقام مراجعة.',
          action: 'قيّم وحدتك',
        },
        {
          title: 'مشتري فرصة',
          body: 'اشتري بسعر تعاقد قديم أقل من السوق وكمل الأقساط بوضوح.',
          action: 'شوف الوحدات',
        },
        {
          title: 'بروكر فريلانسر',
          body: 'سجل العقد وإحنا نراجعه ونقفله ونتابع عمولتك.',
          action: 'سجل عقد',
        },
      ],
    },
    howItWorks: {
      eyebrow: 'إزاي بنشتغل',
      title: 'إزاي بنشتغل؟',
      subtitle: 'خمس خطوات واضحة، ومسؤول حالة معاك في كل خطوة',
      steps: [
        { title: 'قيّم عقدك', body: 'دخّل بيانات عقدك واعرف موقفك مجانًا — وأول ما تبعت طلبك، حسابك بيتجهز تلقائيًا' },
        { title: 'ارفع مستنداتك', body: 'العقد وإيصالات السداد — بنراجعها ونتحقق منها' },
        { title: 'بنجهّز فرصتك', body: 'بنتحقق من الأرقام بالمستندات ونجهز عرض موثوق للمشترين' },
        { title: 'بنلاقي المشتري', body: 'بنطابق وحدتك مع مشترين قادرين فعلًا يكمّلوا' },
        { title: 'نقل التعاقد', body: 'بنمشي معاك في إجراءات النقل خطوة بخطوة لحد ما تقبض' },
      ],
    },
    fairExit: {
      eyebrow: 'مبادئنا',
      title: 'معايير الخروج العادل',
      subtitle: 'وضعنا قواعد ملزمة لنفسنا قبل ما نطلبك تثق فينا',
      items: [
        { title: 'كل رقم له مصدر', body: 'بنوضحلك إيه المؤكد بالمستندات وإيه التقديري — من غير وعود مضللة' },
        { title: 'مجانًا للبايع بالكامل', body: 'مفيش أي عمولة على البايع خالص. المشتري بيدفع 1.25% عند إتمام النقل بس — من غير أي رسوم مخفية' },
        { title: 'خصوصيتك محفوظة', body: 'تقدر تختار الخروج الصامت — مفيش إعلان علني ولا تليفونات مزعجة' },
        { title: 'من غير ضغط', body: 'بنعرض عليك كل الخيارات — حتى لو الأفضل ليك إنك تكمّل تعاقدك' },
      ],
    },
    calculatorCta: {
      title: 'اعرف موقفك في دقيقة',
      subtitle: 'دخّل سعر الوحدة واللي دفعته، وشوف الفرق بين الإلغاء ونقل التعاقد',
      cta: 'احسب دلوقتي',
    },
    dualCta: {
      seller: {
        title: 'مش قادر تكمّل أقساطك؟',
        body: 'متتسرعش في قرار الإلغاء. اعرف موقفك الأول — التقييم مجاني ومن غير أي التزام.',
        cta: 'ابدأ تقييم عقدك',
      },
      buyer: {
        title: 'بتدوّر على فرصة حقيقية؟',
        body: 'سجّل ميزانيتك وهنبعتلك الفرص اللي تناسب الكاش المتاح معاك والقسط اللي يريحك.',
        cta: 'سجّل كمشتري',
      },
    },
    opportunities: {
      eyebrow: 'عروض مختارة',
      title: 'فرص تنازل جاهزة للفحص',
      items: [
        {
          imageKey: safqaAssetKeys.propertyOne,
          title: 'وحدة جاهزة للتنازل',
          location: 'القاهرة الجديدة',
          price: '3,950,000',
          oldPrice: '4,800,000',
          meta: '145 m2 / 3 rooms',
          badge: 'مستندات متحققة',
        },
        {
          imageKey: safqaAssetKeys.propertyTwo,
          title: 'فرصة بسعر أقل من السوق',
          location: '6 أكتوبر',
          price: '5,100,000',
          oldPrice: '6,200,000',
          meta: '210 m2 / townhouse',
          badge: 'تحت المراجعة',
        },
        {
          imageKey: safqaAssetKeys.propertyThree,
          title: 'عقد بروكر قابل للإغلاق',
          location: 'العاصمة الإدارية',
          price: '2,850,000',
          oldPrice: '3,400,000',
          meta: '118 m2 / apartment',
          badge: 'عمولة محفوظة',
        },
      ],
    },
    process: {
      eyebrow: 'رحلة التنازل',
      title: 'خطوات واضحة لحد الإتمام',
      body: 'من أول مراجعة العقد لحد التوقيع وصرف العمولة.',
      items: [
        { title: 'فحص الورق', body: 'العقد، الإيصالات، وجدول الأقساط.' },
        { title: 'تثبيت الأرقام', body: 'المدفوع، المتبقي، وتكلفة التنازل.' },
        { title: 'الإغلاق', body: 'متابعة التوقيع وحالة الصفقة.' },
      ],
    },
    broker: {
      eyebrow: 'للبروكرز',
      title: 'هات الصفقة وإحنا نقفلها',
      body: 'البروكر المستقل يدخل عقده، يتابع الحالة، ويشوف عمولته بوضوح.',
      cards: [
        { value: '24h', label: 'مراجعة أولية' },
        { value: '9d', label: 'متوسط إغلاق' },
        { value: '100%', label: 'حالة موثقة' },
      ],
    },
    command: {
      eyebrow: 'غرفة الصفقة',
      title: 'متابعة واحدة لكل عقد',
      body: 'العميل، الوحدة، المدفوع، المتبقي، المستندات، وحالة التنازل في شاشة واحدة.',
      metrics: [
        { value: '43', label: 'ملف تحت الفحص' },
        { value: '28', label: 'إجراء تنازل' },
        { value: 'EGP 620K', label: 'عمولات قيد الصرف' },
      ],
      queue: [
        { title: 'East Residence A-1407', meta: 'عقد بروكر / 5.8M', status: 'مراجعة' },
        { title: 'West Park T-22', meta: 'تنازل / 9.4M', status: 'حجز تنازل' },
        { title: 'Capital Line B-08', meta: 'فرصة مشتري / 4.1M', status: 'جاهز' },
      ],
    },
    guarantees: {
      eyebrow: 'التوثيق',
      title: 'مفيش رقم من غير مستند',
      items: [
        {
          title: 'فحص العقد',
          body: 'نراجع شروط الإلغاء، التنازل، وأي غرامات ممكنة.',
        },
        {
          title: 'مطابقة الأرقام',
          body: 'المدفوع، المتبقي، الأوفر، وتكلفة التنازل.',
        },
        {
          title: 'حفظ حق البروكر',
          body: 'العمولة تتسجل وتبقى مرتبطة بحالة الإغلاق.',
        },
      ],
    },
    testimonials: {
      eyebrow: 'آراء',
      title: 'ناس خرجت من اللخبطة بوضوح',
      items: [
        { imageKey: safqaAssetKeys.personOne, quote: 'كنت داخل على إلغاء وخسارة، صفقة رتبت الورق وخلت الطريق واضح.', name: 'أحمد سامي', role: 'مالك وحدة' },
        { imageKey: safqaAssetKeys.personTwo, quote: 'اشتريت بسعر تعاقد قديم وكل رقم كان عليه مستند.', name: 'منى خالد', role: 'مشتري فرصة' },
        { imageKey: safqaAssetKeys.personThree, quote: 'سجلت عقد عميلي وفضلت متابع العمولة خطوة بخطوة.', name: 'كريم عادل', role: 'بروكر فريلانسر' },
      ],
    },
    cta: {
      title: 'جاهز تبدأ صفقة موثقة؟',
      body: 'سواء عايز تبيع، تشتري، أو تقفل عقد كبروكر، نبدأ بمراجعة الورق الأول.',
      primary: 'ابدأ الآن',
      secondary: 'تواصل معنا',
    },
    footer: {
      title: 'صفقة',
      body: 'منصة لتوثيق التنازل وإغلاق صفقات البروكرز.',
      phone: '+20 100 000 0000',
      email: 'hello@safqa.realestate',
    },
  },
  en: {
    brand: 'Safqa',
    switchLanguage: 'Arabic',
    nav: {
      home: 'Home',
      paths: 'Paths',
      opportunities: 'Deals',
      process: 'Transfer',
      brokers: 'Brokers',
    },
    hero: {
      eyebrow: 'Property transfer platform — no overprice',
      title: 'Safqa for property transfer deals',
      body: 'The seller recovers every pound paid in cash. The buyer gets the old contract price. Every number is document-verified.',
      primaryCta: 'Sell your unit',
      secondaryCta: 'View buy deals',
      proofLabel: 'Every number',
      proofValue: 'documented',
      heroCard: {
        cancelTitle: 'If he cancels with the developer',
        cancelDeductLabel: 'Cancellation deduction (15% of total unit price)',
        cancelDeductValue: '- 1,500,000 EGP',
        cancelGetLabel: 'What he gets back',
        cancelGetValue: '500,000 EGP',
        cancelYearsLabel: 'Paid over',
        cancelYearsValue: '3 years',
        cancelNote: '75% loss + years of waiting',
        vsLabel: 'VS',
        transferTitle: 'If he transfers via Safqa',
        transferGetLabel: 'He recovers what he paid',
        transferGetValue: '2,000,000 EGP',
        transferGetSub: 'Cash upon transfer completion',
        transferNote: 'Full money back. Buyer wins old price.',
      },
    },
    search: {
      title: 'Find a verified opportunity',
      location: 'Location or compound',
      type: 'Unit type',
      status: 'Deal status',
      submit: 'Search',
    },
    stats: [
      { value: '305+', label: 'files reviewed' },
      { value: '1090+', label: 'indexed opportunities' },
      { value: '67', label: 'partner brokers' },
      { value: '15%', label: 'avoidable cancellation loss' },
    ],
    sellerBuyer: {
      eyebrow: 'Who benefits?',
      title: 'One needs to sell, one is waiting for the deal — we connect them',
      subtitle: "This isn't regular resale: zero overprice. The seller gets exactly what they paid. The buyer gets the old contract price as-is.",
      seller: {
        tag: 'Seller — unit owner',
        title: 'No overprice = fastest sale in the market',
        body: 'Because your price is exactly what you paid with zero markup, your unit becomes the most attractive opportunity for buyers — and sells faster. You recover your full investment in cash instead of the developer deducting and installmenting your refund over years.',
        features: [
          'Recover 100% of what you paid — cash upon transfer completion',
          'No public ads, no broker calls',
          'We prepare your transfer file and follow up step by step until signing',
        ],
        freeNote: 'Completely free for you — Safqa charges zero commission from the seller.',
        cta: 'List your unit for transfer',
      },
      buyer: {
        tag: 'Buyer',
        title: 'An installment unit without paying overprice to anyone',
        body: 'You get the unit at its old contract price — significantly below today\'s market — and continue the regular installments. That difference is your profit from the day you sign.',
        features: [
          'Old contract price as-is — overprice is prohibited on the platform',
          'Contract, payments, and remaining balance all verified before you see the deal',
          'Official transfer approved by the developer — no proxy letters',
        ],
        cta: 'View available deals',
      },
    },
    comparison: {
      eyebrow: 'The real difference',
      title: 'How do we differ from regular resale?',
      subtitle: "The market is full of ads and brokers — we operate very differently",
      rows: [
        { label: 'Price', regular: 'Overprice on top, inflated for negotiation', safqa: 'No overprice — price = what was actually paid, documented with receipts' },
        { label: 'Numbers', regular: "Seller and broker's word with no evidence", safqa: 'Contract, payments, and remaining balance verified with official documents' },
        { label: 'Process', regular: "Broker connects you then you're on your own", safqa: 'We walk with you through every transfer step until signing and collection' },
        { label: 'Commission', regular: 'Brokerage from both sides at every step, surprises included', safqa: 'Free for seller — 1.25% from buyer only, upon transfer completion' },
      ],
    },
    numbersExample: {
      eyebrow: 'Real example',
      title: 'Numbers example',
      subtitle: 'Unit total price 10M EGP. Owner paid 2M over 3 years and stopped payments.',
      cancelCard: {
        title: 'If he cancels with the developer',
        deductLabel: 'Cancellation deduction (15% of total)',
        deductValue: '- 1,500,000 EGP',
        getLabel: 'What he gets back',
        getValue: '500,000 EGP',
        yearsLabel: 'Paid over',
        yearsValue: '3 years',
        note: '75% loss + years of waiting',
      },
      transferCard: {
        title: 'If he transfers via Safqa',
        getLabel: 'He recovers what he paid',
        getValue: '2,000,000 EGP',
        getSub: 'Cash upon transfer completion',
        feeLabel: "Safqa's commission from seller",
        feeValue: 'Zero',
        feeSub: 'Pays nothing — receives full amount',
        note: 'Full money back. Buyer wins old price.',
      },
      disclaimer: "These numbers are illustrative. Deduction rates and recovery terms vary per contract — that's exactly what we review in the free exit report.",
    },
    paths: {
      eyebrow: 'Paths',
      title: 'Three problems, one clear solution',
      items: [
        {
          title: 'Distressed owner',
          body: 'List your unit for transfer with verified numbers instead of losing money through cancellation.',
          action: 'Value my unit',
        },
        {
          title: 'Opportunity buyer',
          body: 'Buy at an older contract price below today market and continue the installments clearly.',
          action: 'View units',
        },
        {
          title: 'Freelance broker',
          body: 'Register the contract, let Safqa close it, and track your commission in one place.',
          action: 'Register contract',
        },
      ],
    },
    howItWorks: {
      eyebrow: 'How we work',
      title: 'How do we work?',
      subtitle: 'Five clear steps, with a case manager by your side at every step',
      steps: [
        { title: 'Assess your contract', body: 'Enter your contract details and know your situation for free — once you submit, your account is set up automatically' },
        { title: 'Upload your documents', body: 'Contract and payment receipts — we review and verify them' },
        { title: 'We prepare your deal', body: 'We verify numbers with documents and prepare a trusted listing for buyers' },
        { title: 'We find the buyer', body: 'We match your unit with buyers who can genuinely continue the payments' },
        { title: 'Contract transfer', body: 'We walk with you through transfer procedures step by step until you collect' },
      ],
    },
    fairExit: {
      eyebrow: 'Our principles',
      title: 'Fair exit standards',
      subtitle: 'We set binding rules for ourselves before asking for your trust',
      items: [
        { title: 'Every number has a source', body: "We show you what's confirmed by documents vs. what's estimated — no misleading promises" },
        { title: 'Completely free for sellers', body: 'Zero commission from the seller. The buyer pays 1.25% only upon transfer completion — no hidden fees' },
        { title: 'Your privacy is protected', body: 'You can choose the silent exit — no public listing, no annoying calls' },
        { title: 'Zero pressure', body: "We present all your options — even if the best choice for you is to continue your contract" },
      ],
    },
    calculatorCta: {
      title: 'Know your situation in one minute',
      subtitle: 'Enter the unit price and what you paid, and see the difference between cancellation and transfer',
      cta: 'Calculate now',
    },
    dualCta: {
      seller: {
        title: "Can't continue your installments?",
        body: "Don't rush into a cancellation decision. Know your situation first — the assessment is free with no obligation.",
        cta: 'Start contract assessment',
      },
      buyer: {
        title: 'Looking for a real opportunity?',
        body: 'Register your budget and we\'ll send you deals that match your available cash and comfortable installment.',
        cta: 'Register as buyer',
      },
    },
    opportunities: {
      eyebrow: 'Selected offers',
      title: 'Transfer opportunities ready for review',
      items: [
        {
          imageKey: safqaAssetKeys.propertyOne,
          title: 'Unit ready for transfer',
          location: 'New Cairo',
          price: '3,950,000',
          oldPrice: '4,800,000',
          meta: '145 m2 / 3 rooms',
          badge: 'Documents verified',
        },
        {
          imageKey: safqaAssetKeys.propertyTwo,
          title: 'Below-market opportunity',
          location: '6th October',
          price: '5,100,000',
          oldPrice: '6,200,000',
          meta: '210 m2 / townhouse',
          badge: 'Under review',
        },
        {
          imageKey: safqaAssetKeys.propertyThree,
          title: 'Broker contract ready to close',
          location: 'New Capital',
          price: '2,850,000',
          oldPrice: '3,400,000',
          meta: '118 m2 / apartment',
          badge: 'Commission protected',
        },
      ],
    },
    process: {
      eyebrow: 'Transfer journey',
      title: 'Clear steps until completion',
      body: 'From contract review to signature and commission payout.',
      items: [
        { title: 'Document audit', body: 'Contract, receipts, and installment schedule.' },
        { title: 'Number confirmation', body: 'Paid amount, remaining balance, and transfer costs.' },
        { title: 'Closing', body: 'Follow signature and deal status through completion.' },
      ],
    },
    broker: {
      eyebrow: 'For brokers',
      title: 'Bring the deal, we close it',
      body: 'The independent broker enters the contract, follows the status, and sees commission progress clearly.',
      cards: [
        { value: '24h', label: 'initial review' },
        { value: '9d', label: 'average closing' },
        { value: '100%', label: 'tracked status' },
      ],
    },
    command: {
      eyebrow: 'Deal command room',
      title: 'One live view for every contract',
      body: 'Client, unit, paid amount, remaining balance, documents, and transfer status in one operational screen.',
      metrics: [
        { value: '43', label: 'files under audit' },
        { value: '28', label: 'transfer actions' },
        { value: 'EGP 620K', label: 'payouts pending' },
      ],
      queue: [
        { title: 'East Residence A-1407', meta: 'Broker contract / 5.8M', status: 'Review' },
        { title: 'West Park T-22', meta: 'Transfer / 9.4M', status: 'Booking' },
        { title: 'Capital Line B-08', meta: 'Buyer opportunity / 4.1M', status: 'Ready' },
      ],
    },
    guarantees: {
      eyebrow: 'Verification',
      title: 'No number without a document',
      items: [
        {
          title: 'Contract audit',
          body: 'We review cancellation, transfer terms, and any possible penalties.',
        },
        {
          title: 'Number matching',
          body: 'Paid amount, remaining balance, overprice, and transfer costs.',
        },
        {
          title: 'Broker rights',
          body: 'Commission is registered and tied to the closing status.',
        },
      ],
    },
    testimonials: {
      eyebrow: 'Reviews',
      title: 'People who moved from confusion to clarity',
      items: [
        {
          imageKey: safqaAssetKeys.personOne,
          quote: 'I was heading toward cancellation and a loss. Safqa organized the documents and made the path clear.',
          name: 'Ahmed Samy',
          role: 'Unit owner',
        },
        {
          imageKey: safqaAssetKeys.personTwo,
          quote: 'I bought at an older contract price, and every number had a document behind it.',
          name: 'Mona Khaled',
          role: 'Opportunity buyer',
        },
        {
          imageKey: safqaAssetKeys.personThree,
          quote: 'I registered my client contract and tracked commission status step by step.',
          name: 'Karim Adel',
          role: 'Freelance broker',
        },
      ],
    },
    cta: {
      title: 'Ready to start a documented deal?',
      body: 'Whether you want to sell, buy, or close a contract as a broker, the first step is a clean document review.',
      primary: 'Start now',
      secondary: 'Contact us',
    },
    footer: {
      title: 'Safqa',
      body: 'A platform for documented transfers and broker deal closing.',
      phone: '+20 100 000 0000',
      email: 'hello@safqa.realestate',
    },
  },
}
